### ISSUE TITLE
No such file or directory: 'sbatch': 'sbatch'

### ISSUE THREAD

**Issue by cvoelcker** [e2crawfo/auto_yolo#1]
Hi, while trying to run the demo, I'm getting the following error
```
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'sbatch': 'sbatch'
```
Do you have any idea why that might be the case? The same error also appears, if I try to run your DPS sample script, so I'm guessing it might be located there. Does the code require slurm on the machine?

Full error trace
```
Traceback (most recent call last):              
  File "yolo_air_run.py", line 41, in <module>  
    alg="yolo_air", task="arithmetic", durations=durations,                                      
  File "/home/cvoelcker/thesis/auto_yolo/auto_yolo/envs.py", line 92, in run_experiment          
    name=exp_name, config=_config, distributions=distributions, **run_kwargs)                    
  File "/home/cvoelcker/thesis/dps/dps/hyper/base.py", line 622, in build_and_submit             
    parallel_session = submit_job(**run_kwargs) 
  File "/home/cvoelcker/thesis/dps/dps/hyper/parallel_session.py", line 840, in submit_job
    subprocess.run(command.split())
  File "/usr/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'sbatch': 'sbatch'
```

**Comment by cvoelcker** [comment]
I tested it, it was slurm

**Comment by SamWangGibhub** [comment]
> I tested it, it was slurm

How to solve it?
when I run $ qlaunch singleshot
error:"FileNotFoundError: [Errno 2] No such file or directory: 'sbatch'"
"raise RuntimeError(
RuntimeError: queue script could not be submitted, check queue script/queue adapter/queue server status!"
Thanks.
