### ISSUE TITLE
Cannot load 'cfg' from dps

### ISSUE THREAD

**Issue by erlebach** [e2crawfo/auto_yolo#6]

**Comment by erlebach** [comment]
Hi, 

Running on a Macbook Pro with no GPU with CUDA, I ran the test with dps and got an error. Any ideas? 

dps erlebach$ dps-run simple_addition a2c
Traceback (most recent call last):
  File "/Users/erlebach/anaconda3/envs/tensorflow/bin/dps-run", line 11, in <module>
    load_entry_point('dps', 'console_scripts', 'dps-run')()
  File "/Users/erlebach/anaconda3/envs/tensorflow/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/erlebach/anaconda3/envs/tensorflow/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/Users/erlebach/anaconda3/envs/tensorflow/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/Users/erlebach/anaconda3/envs/tensorflow/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/erlebach/Documents/src/2019/auto_yolo/dps/dps/__init__.py", line 7, in <module>
    from .config import DEFAULT_CONFIG
  File "/Users/erlebach/Documents/src/2019/auto_yolo/dps/dps/config.py", line 3, in <module>
    from dps.utils import Config, load_system_config
  File "/Users/erlebach/Documents/src/2019/auto_yolo/dps/dps/utils/__init__.py", line 1, in <module>
    from .base import *
  File "/Users/erlebach/Documents/src/2019/auto_yolo/dps/dps/utils/base.py", line 13, in <module>
    import psutil
  File "/Users/erlebach/anaconda3/envs/tensorflow/lib/python3.7/site-packages/psutil/__init__.py", line 156, in <module>
    from . import _psosx as _psplatform
  File "/Users/erlebach/anaconda3/envs/tensorflow/lib/python3.7/site-packages/psutil/_psosx.py", line 15, in <module>
    from . import _psutil_osx as cext
ImportError: dlopen(/Users/erlebach/anaconda3/envs/tensorflow/lib/python3.7/site-packages/psutil/_psutil_osx.cpython-37m-darwin.so, 2): Symbol not found: ___CFConstantStringClassReference
  Referenced from: /Users/erlebach/anaconda3/envs/tensorflow/lib/python3.7/site-packages/psutil/_psutil_osx.cpython-37m-darwin.so
  Expected in: flat namespace
 in /Users/erlebach/anaconda3/envs/tensorflow/lib/python3.7/site-packages/psutil/_psutil_osx.cpython-37m-darwin.so

**Comment by erlebach** [comment]
Hi, 

I tried to download the data using dps, and it did not work. Perhaps i could download the data manually? 

Question: Is there a Pytorch implementation of your auto_yolo software? Thanks.

(tensorflow) Gordons-MBP-2:scripts erlebach$ python download.py emnist --shape=14,14
[TerminalIPythonApp] WARNING | Unrecognized alias: '--shape=14,14', it will probably have no effect.
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~/Documents/src/2019/auto_yolo/dps/scripts/download.py in <module>
     11 
     12 from dps import cfg
---> 13 from dps.datasets.load import _validate_emnist
     14 from dps.utils import image_to_string, cd, process_path
     15 from dps.datasets.load import convert_emnist_and_store

ImportError: cannot import name '_validate_emnist' from 'dps.datasets.load' (/Users/erlebach/Documents/src/2019/auto_yolo/dps/dps/datasets/load/__init__.py)
(tensorflow) Gordons-MBP-2:scripts erlebach$ python download.py emnist
\---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~/Documents/src/2019/auto_yolo/dps/scripts/download.py in <module>
     11 
     12 from dps import cfg
---> 13 from dps.datasets.load import _validate_emnist
     14 from dps.utils import image_to_string, cd, process_path
     15 from dps.datasets.load import convert_emnist_and_store

ImportError: cannot import name '_validate_emnist' from 'dps.datasets.load' (/Users/erlebach/Documents/src/2019/auto_yolo/dps/dps/datasets/load/__init__.py)
